# ideally we would define this with SteamCMD's force_install_dir option or something, but idk how to use it...
RDS_ABSOLUTE_PATH="/home/rust/Steam/steamapps/common/rust_dedicated/RustDedicated"

# hopefully this is not too volatile...
STEAMCMD_ABSOLUTE_PATH="/usr/games/steamcmd"
